version: "3" ## especifica a versão do docker-compose file

services: 
  app: 
    build: . 
    command: npm run dev
    environment:
      CLIENT_TOKEN: 
      TEST_GUILD: 
    ports:
      - "53011:3000" 
    volumes:
      - .:/usr/app 